# Generated by Django 3.1.7 on 2021-03-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSigns',
            fields=[
                ('RoadSignId', models.AutoField(primary_key=True, serialize=False)),
                ('RoadSignName', models.CharField(max_length=255)),
                ('RoadSignCategory', models.CharField(max_length=255)),
                ('PhotoFileName', models.CharField(max_length=255)),
            ],
        ),
    ]
